### ISSUE TITLE
Create Batch script for install?

### ISSUE THREAD

**Issue by pgensler** [rpaugh/Alteryx-Outlook-Tools#2]
Hi,

I was trying to install this add-in into my Alteryx, and I noticed the version on the Gallery was using an exe file, which it seems like my work laptop does not like due to not enough administrative privileges to install. Is there a way to install the add-in via a Batch script instead of using the InstallShield Wizard? In my experience, using a batch script has done the trick(see Omnibus-tools as a good example of this https://github.com/jdunkerley/AlteryxAddIns/releases/).
 I'm really looking forwarding to messing around with this macro to put to good use. Thanks.

**Comment by rpaugh** [comment]
Funny you mention the Omnibus tools example because I tried that route first but couldn't get it to work (I couldn't even get the Omnibus tools to install).  If you download and build the project from here you could always simply copy the DLLs over to the appropriate Alteryx directory on your computer.

**Comment by pgensler** [comment]
@rpaugh hmm I know James had made some modifications to his batch scripts where I think it assumed I had the R tools installed, which was causing some issues in the folder structure. I have not kept up with his releases recently so I'm betting things probably have changed. I can definitely try to re-download his latest release, and see if anything major changed.

As far as DLL's go, I have not dug too far into how those components work in Alteryx. Where would they need to go to make things run smoothly?

**Comment by rpaugh** [comment]
I tried his batch script back in late June/early July, so I don't know if his latest update was before or after that.  I also tried creating my own to do the install, but couldn't get that to work right either for some reason.

To manually install the tool do the following (assuming Alteryx is installed to the default location):

1. Place the OutlookInputPlugin.ini file in C:\Program Files\Alteryx\Settings\AdditionalPlugins
2. Place the compiled DLLs in C:\Program Files\Alteryx\Outlook

**Comment by pgensler** [comment]
Which release did you try? I believe James has two releases due to some differences with a powershell vs batch script approach(both you can download and find here):
https://github.com/jdunkerley/AlteryxAddIns/releases. I would try the ```AlteryxOmniBus.v0.5.4.1.NoPowerShell.zip```, and see if that works.
